export type ApiProblem = { status: number; message: string; requestId?: string; network?: boolean }
export type WorkspaceSession = { workspaceId: string; userId: string; userName?: string }

const baseUrl = (import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/$/, '')

export class ApiClientError extends Error {
  problem: ApiProblem
  constructor(problem: ApiProblem) { super(problem.message); this.problem = problem }
}

function headers(session?: WorkspaceSession, extra: HeadersInit = {}) {
  const output = new Headers(extra)
  output.set('accept', 'application/json')
  if (session) { output.set('x-user-id', session.userId); output.set('x-workspace-id', session.workspaceId) }
  return output
}

export async function request<T>(path: string, options: RequestInit & { session?: WorkspaceSession } = {}): Promise<T> {
  const controller = options.signal ? null : new AbortController()
  try {
    const response = await fetch(baseUrl + path, { ...options, headers: headers(options.session, options.headers), signal: options.signal ?? controller?.signal })
    const payload = await response.json().catch(() => ({})) as { error?: string; requestId?: string } & T
    if (!response.ok) throw new ApiClientError({ status: response.status, message: payload.error ?? ('请求失败（' + response.status + '）'), requestId: payload.requestId })
    return payload as T
  } catch (error) {
    if (error instanceof ApiClientError || error instanceof DOMException) throw error
    throw new ApiClientError({ status: 0, network: true, message: '无法连接本地 API。请确认 8787 服务正在运行。' })
  } finally { controller?.abort() }
}

export function developmentBootstrap() { return request<{ sample: { workspace: { id: string; name: string }; administrator: { id: string; name: string }; marketPacks: Array<{ id: string }> } }>('/api/development/sample-workspace', { method: 'POST' }) }
export function developmentEmptyWorkspace() { return request<{ workspace: { id: string; name: string }; administrator: { id: string; name: string } }>('/api/development/empty-workspace', { method: 'POST' }) }
export type OnboardingMarketInput = { market: 'CN' | 'GLOBAL'; locale: 'zh-CN' | 'en-US'; providers: string[]; channels: string[] }
export type OnboardingRequest = { workspaceName: string; administrator: { id: string; name: string }; brandName: string; website: string; industry: string; audience: string; objective: string; competitors: string[]; markets: OnboardingMarketInput[]; queryTarget: number }
export type DiagnosticProject = { id: string; brandName: string; website: string; industry: string; audience: string; objective: string; status: 'draft' | 'ready-for-review' | 'collecting' | 'completed' | 'archived'; markets: OnboardingMarketInput[]; competitors: string[]; primaryEvidencePackId: string }
export type CollectionPlan = { id: string; projectId: string; marketPackId: string; datasetId: string; assessmentRunId: string | null; providerId: string; collectionMode: 'controlled-manual'; status: 'planned' | 'collecting' | 'imported' | 'blocked' | 'failed'; instructions: string; coverage: { expected: number; imported: number; remaining: number; isComplete: boolean } }
export type DiagnosticSetup = { workspace: { id: string; name: string; brand: string }; project: DiagnosticProject; evidencePack: { id: string; status: string; items: Array<{ id: string; title: string }> }; marketPacks: MarketPack[]; datasets: Dataset[]; collectionPlans: CollectionPlan[]; nextStep: string; limitations: string[]; collectionBoundary: string }
export function onboardWorkspace(input: OnboardingRequest) { return request<{ workspace: { id: string; name: string; brand: string }; setup: DiagnosticSetup; session: WorkspaceSession }>('/api/workspaces/onboard', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function onboardExistingWorkspace(session: WorkspaceSession, input: Omit<OnboardingRequest, 'administrator' | 'workspaceName'>) { return request<{ workspace: { id: string; name: string; brand: string }; setup: DiagnosticSetup }>('/api/workspaces/' + session.workspaceId + '/onboard', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function getDiagnosticSetup(session: WorkspaceSession) { return request<{ setup: DiagnosticSetup | null }>('/api/workspaces/' + session.workspaceId + '/diagnostic-setup', { session }) }
export function activateDiagnosticProject(session: WorkspaceSession, projectId: string, reviewComment: string) { return request<{ setup: DiagnosticSetup }>('/api/workspaces/' + session.workspaceId + '/diagnostic-projects/' + projectId + '/activate', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ reviewComment }) }) }
export function getWorkspace(session: WorkspaceSession) { return request<{ workspace: { id: string; name: string; brand: string } }>('/api/workspaces/' + session.workspaceId, { session }) }
export function listMarketPacks(session: WorkspaceSession) { return request<{ marketPacks: Array<MarketPack> }>('/api/workspaces/' + session.workspaceId + '/market-packs', { session }) }
export function getDashboard(session: WorkspaceSession, marketPackId: string, params: { assessmentRunId?: string; baselineRunId?: string } = {}) {
  const search = new URLSearchParams(); if (params.assessmentRunId) search.set('assessmentRunId', params.assessmentRunId); if (params.baselineRunId) search.set('baselineRunId', params.baselineRunId)
  return request<{ dashboard: Dashboard }>('/api/workspaces/' + session.workspaceId + '/market-packs/' + marketPackId + '/dashboard' + (search.size ? '?' + search : ''), { session })
}
export function getArtifact(session: WorkspaceSession, artifactId: string) { return request<{ payload: { rawAnswer?: string; citations?: Citation[] } }>('/api/workspaces/' + session.workspaceId + '/artifacts/' + artifactId, { session }) }
export function createArtifact(session: WorkspaceSession, kind: string, payload: unknown) { return request<{ artifact: { id: string } }>('/api/workspaces/' + session.workspaceId + '/artifacts', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind, payload }) }) }
export function importManualObservation(session: WorkspaceSession, assessmentRunId: string, input: { queryId: string; providerId: string; modelIdentity: string; collectedAt: string; sourceRef: string; supportingArtifactId: string; rawAnswer: string; citations: Citation[]; analysis: Record<string, unknown> }) { return request<{ observation: Observation }>('/api/workspaces/' + session.workspaceId + '/assessment-runs/' + assessmentRunId + '/observations/import', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function claimNextObservation(session: WorkspaceSession, assessmentRunId: string, providerId?: string, options?: { resumeOnly?: boolean }) { const body = { ...(providerId ? { providerId } : {}), ...(options?.resumeOnly ? { resumeOnly: true } : {}) }; return request<{ observation: Observation | null; run: AssessmentRun }>('/api/workspaces/' + session.workspaceId + '/assessment-runs/' + assessmentRunId + '/observations/claim-next', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) }
export function generateEvidenceGroundedDiagnoses(session: WorkspaceSession, assessmentRunId: string) { return request<{ diagnoses: Diagnosis[]; reused?: boolean }>('/api/workspaces/' + session.workspaceId + '/assessment-runs/' + assessmentRunId + '/diagnoses/generate', { method: 'POST', session }) }
export function listResources(session: WorkspaceSession) { return Promise.all([
  request<{ datasets: Dataset[] }>('/api/workspaces/' + session.workspaceId + '/datasets', { session }),
  request<{ briefs: ContentBrief[] }>('/api/workspaces/' + session.workspaceId + '/content-briefs', { session }),
  request<{ drafts: ContentDraft[] }>('/api/workspaces/' + session.workspaceId + '/content-drafts', { session }),
  request<{ tasks: DistributionTask[] }>('/api/workspaces/' + session.workspaceId + '/distribution-tasks', { session }),
  request<{ reports: Report[] }>('/api/workspaces/' + session.workspaceId + '/reports', { session }),
])
}

export type MonitoringPlan = { id: string; workspaceId: string; marketPackId: string; datasetId: string; queryId: string; label: string; providerIds: string[]; cadence: 'daily' | 'weekly'; status: 'active' | 'paused' | 'archived'; lastAssessmentRunId: string | null; lastCheckedAt: string | null; nextCheckAt: string | null; createdAt: string; updatedAt: string; createdBy: string; query: { id: string; text: string } | null; lastRun: { id: string; label: string; status: string; isComplete: boolean; completion: AssessmentRun['completion'] } | null }
export function listMonitoringPlans(session: WorkspaceSession, marketPackId?: string) { return request<{ plans: MonitoringPlan[]; collectionBoundary: string }>('/api/workspaces/' + session.workspaceId + '/monitoring-plans' + (marketPackId ? '?marketPackId=' + encodeURIComponent(marketPackId) : ''), { session }) }
export function createMonitoringPlan(session: WorkspaceSession, input: { marketPackId: string; queryId: string; providerIds: string[]; cadence: 'daily' | 'weekly'; label?: string }) { return request<{ plan: MonitoringPlan }>('/api/workspaces/' + session.workspaceId + '/monitoring-plans', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function queueMonitoringRecheck(session: WorkspaceSession, planId: string) { return request<{ plan: MonitoringPlan; run: AssessmentRun; collectionBoundary: string }>('/api/workspaces/' + session.workspaceId + '/monitoring-plans/' + planId + '/queue-recheck', { method: 'POST', session }) }
export function updateMonitoringPlanStatus(session: WorkspaceSession, planId: string, status: MonitoringPlan['status']) { return request<{ plan: MonitoringPlan }>('/api/workspaces/' + session.workspaceId + '/monitoring-plans/' + planId, { method: 'PATCH', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) }) }
export type Citation = { url: string; kind: 'owned' | 'third-party' | 'unknown' }
export type MarketPack = { id: string; label: string; market: string; locale: string; providers: string[]; channels: string[]; competitors: string[]; audience: string; status: string }
export type Metric = { numerator: number; denominator: number; rate: number | null; observationIds?: string[] }
export type AssessmentRun = { id: string; label: string; status: string; createdAt: string; isComplete: boolean; datasetId: string; datasetVersion: number; marketPackId: string; locale: string; providers: string[]; cohortQueryIds: string[]; completion: { planned: number; queued: number; collecting: number; completed: number; imported: number; failed: number; resolved: number; isComplete: boolean; incompleteReason: string | null } }
export type Observation = { id: string; queryId: string; providerId: string; modelIdentity?: string; status: string; collectedAt?: string; sourceRef?: string; rawArtifactId?: string; citations: Citation[]; analysis: { brandMentioned?: boolean; recommended?: boolean; competitorsMentioned?: string[]; competitorsRecommended?: string[]; claims?: Array<{ statement: string; assessment: string }> }; error?: { message?: string } | null }
export type Diagnosis = { id: string; title: string; priority: string; category: string; confidence: string; detail: string; recommendation: string; uncertainty: string; queryIds: string[]; observationIds: string[] }
export type Dashboard = { workspace: { id: string; name: string; brand: string }; marketPack: MarketPack; context: { selectedRun: AssessmentRun | null; baselineRun: AssessmentRun | null; availableRuns: Array<Pick<AssessmentRun, 'id'|'label'|'status'|'createdAt'|'isComplete'|'datasetVersion'|'locale'>>; dataset: Dataset | null }; measurement: { eligibleObservationCount: number; statusCounts: Record<string, number>; exclusions: Record<string, number | boolean>; metrics: Record<string, Metric> } | null; completeness: { isComplete: boolean; providerCoverage: Array<{ providerId: string; expected: number; observed: number; byStatus: Record<string, number> }> } | null; comparison: { comparable: boolean; reason?: string; deltas?: Record<string, { delta: number | null; baseline: number | null; followUp: number | null }> } | null; diagnoses: Diagnosis[]; actions: Array<DistributionTask & { draft?: { id: string; title: string; status: string } | null; brief?: { id: string; title: string; status: string; channel: string; targetQueryIds: string[] } | null; diagnosis?: { id: string; title: string; priority: string; recommendation: string } | null }>; evidence: { observationCount: number; observations: Observation[] }; competitorResearch: Array<{ id: string; sourceRef: string; sourceType: string; findings: Record<string, unknown>; collectedAt: string; extractionStatus: string }>; reports: Report[]; workflowReadiness: { stage: string; nextAllowedOperation: string; blockingReasons: string[]; ready: boolean }; limitations: string[]; collectionBoundary: string }
export type Dataset = { id: string; label: string; logicalKey: string; version: number; status: string; queries: Array<{ id: string; text: string; market: string; locale: string; intent: string; priority: string; expectedFacts: string[] }> }
export type ContentTaskInput = { audience?: string; objective?: string; funnelStage?: 'awareness'|'consideration'|'decision'|'retention'|string; cta?: string; channel?: string; format?: string; customInstruction?: string }
export type QueryEvidenceSelectionInput = { queryGroupId: string; competitorLinkCandidateIds?: string[] }
export type ContentBrief = { id: string; projectId?: string | null; title: string; status: string; channel: string; contentType: string; diagnosisId?: string | null; marketPackId?: string | null; evidencePackId?: string | null; evidencePackVersion?: number | null; contentStrategyId?: string | null; aiInvocationId?: string; locale?: string; version?: number; sourceContext?: Record<string, unknown>; brief: { targetQueries?: Array<{ id: string; text: string; intent?: string }>; contentTask?: ContentTaskInput & { primaryQuery?: string }; queryEvidence?: { queryGroupId: string; question: string; approvedAnswerCount: number; platforms: string[]; modelAnswers: Array<{ evidenceId: string; platform: string; answerExcerpt: string }>; competitorLinks: Array<{ id: string; url: string; title: string; domain: string }>; competitorInsights: Array<{ id: string; agentType: string; resultExcerpt?: string }>; evidenceBoundary: string } | null; outline?: string[]; reviewCriteria?: string[]; mandatoryFacts?: Array<{ statement: string; sourceRef?: string; evidenceId?: string }>; prohibitedClaims?: string[]; sourceLinks?: string[]; competitorContext?: Array<{ name: string; treatment: string }>; aiPlan?: { text?: string; model?: string; promptTemplateVersion?: string }; [key: string]: unknown } }
export type ContentDraft = { id: string; projectId?: string | null; title: string; status: string; sourceBriefId: string; channel: string; contentType: string; aiInvocationId?: string; version?: number; sourceContext?: Record<string, unknown>; draft?: { contentMarkdown?: string; generationBoundary?: string; prohibitedClaims?: string[]; sourceLinks?: string[]; sections?: Array<{ heading: string; body: string }>; [key: string]: unknown } }
export type DraftClaimValidation = { id: string; contentDraftId: string; statement: string; claimType: string; evidenceRefs: string[]; status: 'unresolved'|'supported'|'rejected'; resolutionComment?: string | null }
export type ApprovedContentSnapshot = { id: string; contentDraftId: string; draftVersion: number; content: ContentDraft['draft']; claimValidations: DraftClaimValidation[]; approvedAt: string; approvedBy: string; reviewComment: string }
export type ContentDeliveryPackage = { schemaVersion: string; filename: string; exportedAt: string; projectId: string | null; strategyId: string | null; briefId: string; draftId: string; snapshotId: string; channel: string; contentType: string; metadata: Record<string, unknown>; markdown: string; evidenceMap: { targetQueries: Array<Record<string, unknown>>; mandatoryFacts: Array<Record<string, unknown>>; sourceLinks: string[]; claims: Array<Record<string, unknown>>; evidenceBoundary: string }; publishingChecklist: string[]; followUpScope: { testRunId: string | null; assessmentRunId: string | null; datasetId: string | null; targetQueryIds: string[]; boundary: string }; boundary: string }
export type DistributionTask = { id: string; contentDraftId: string; approvedSnapshotId?: string; ownerId: string; channel: string; targetQueryIds: string[]; status: string; scheduledFor: string; notes?: string | null }
export type ContentPromptProfile = { id: string; version: string | number; name: string; description: string; tone: string; channelGuidance?: string; systemInstruction?: string; outputContract?: string; channelTags?: string[]; contentTypeTags?: string[]; source?: 'builtin'|'workspace'; editable?: boolean; status?: 'active'|'archived'; createdAt?: string; updatedAt?: string }
export type ContentPromptProfileInput = { name: string; description: string; tone: string; channelGuidance: string; systemInstruction: string; outputContract: string; channelTags: string[]; contentTypeTags: string[] }
export type ContentPlan = { strategy: ContentStrategy; brief: ContentBrief; geoGapAction?: GeoGapAction | null; aiInvocation: { id: string; modelIdentity?: string | null; promptTemplateVersion?: string }; executionBoundary: string }
export type ContentStrategy = { id: string; projectId?: string | null; logicalKey: string; version: number; status: string; diagnosisId?: string | null; marketPackId?: string | null; evidencePackId?: string | null; evidencePackVersion?: number | null; queryIds: string[]; channels: string[]; title: string; objective: string; strategy: { gapSummary?: string; assets?: Array<{ channel: string; contentType: string; title: string }>; cta?: string; linkingGuidance?: string; acceptanceCriteria?: string[]; prohibitedClaims?: string[]; sourcePack?: string[]; competitorEvidence?: string[]; [key: string]: unknown }; sourceContext?: Record<string, unknown>; createdAt: string; reviewComment?: string | null }
export type ContentPublication = { id: string; projectId?: string | null; approvedSnapshotId: string; contentDraftId: string; contentBriefId: string; contentStrategyId?: string | null; sourceAssessmentRunId?: string | null; datasetId?: string | null; channel: string; publishedUrl: string; publishedAt: string; proofArtifactId: string; targetQueryIds: string[]; sourceContext?: Record<string, unknown>; status: 'registered'|'retest-planned'|'archived'; retestPlan?: { scheduledFor: string; cadence: 'once'|'weekly'|'monthly'; datasetId: string; targetQueryIds: string[]; [key: string]: unknown } | null; notes?: string | null }
export type PublicationProofInput = { evidenceUrl?: string; description?: string; proofArtifactId?: string }
export type PublicationObservationMetric = { numerator: number; denominator: number; rate: number | null }
export type ContentPublicationObservation = {
  publication: ContentPublication
  baselineRun: AssessmentRun | null
  followUpRun: AssessmentRun | null
  status: 'not-scheduled'|'scheduled'|'awaiting-evidence'|'ready'|'not-comparable'
  scope: { datasetId: string; datasetVersion?: number; marketPackId?: string; locale?: string; targetQueryIds: string[]; sourceAssessmentRunId: string; providers: string[] }
  observation: {
    comparable: boolean
    baseline: { mentionRate: PublicationObservationMetric; recommendationRate: PublicationObservationMetric; ownedCitationRate: PublicationObservationMetric; sampleSize: number } | null
    followUp: { mentionRate: PublicationObservationMetric; recommendationRate: PublicationObservationMetric; ownedCitationRate: PublicationObservationMetric; sampleSize: number } | null
    deltas: { mentionRate: number | null; recommendationRate: number | null; ownedCitationRate: number | null } | null
    limitations: string[]
  }
  boundary: string
}
export type Report = { id: string; title: string; status: string; baselineRunId?: string | null; followUpRunId?: string | null; limitations: string[]; report: Record<string, unknown>; createdAt: string }

export function listContentPromptProfiles(session: WorkspaceSession) { return request<{ profiles: ContentPromptProfile[] }>('/api/workspaces/' + session.workspaceId + '/content-prompt-profiles', { session }) }
export function getContentPromptProfile(session: WorkspaceSession, profileId: string) { return request<{ profile: ContentPromptProfile }>('/api/workspaces/' + session.workspaceId + '/content-prompt-profiles/' + profileId, { session }) }
export function createContentPromptProfile(session: WorkspaceSession, input: ContentPromptProfileInput) { return request<{ profile: ContentPromptProfile }>('/api/workspaces/' + session.workspaceId + '/content-prompt-profiles', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function updateContentPromptProfile(session: WorkspaceSession, profileId: string, input: ContentPromptProfileInput) { return request<{ profile: ContentPromptProfile }>('/api/workspaces/' + session.workspaceId + '/content-prompt-profiles/' + profileId, { method: 'PUT', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function archiveContentPromptProfile(session: WorkspaceSession, profileId: string) { return request<{ profile: ContentPromptProfile }>('/api/workspaces/' + session.workspaceId + '/content-prompt-profiles/' + profileId + '/archive', { method: 'POST', session }) }
export function deleteContentPromptProfile(session: WorkspaceSession, profileId: string) { return request<{ deletedProfileId: string }>('/api/workspaces/' + session.workspaceId + '/content-prompt-profiles/' + profileId, { method: 'DELETE', session }) }
export function generateAiContentPlan(session: WorkspaceSession, diagnosisId: string, input: { logicalKey: string; marketPackId: string; targetQueryIds: string[]; channel: string; contentType: 'website-page'|'faq'|'use-case'|'comparison-page'|'case-study'|'editorial'; title: string; writingProfileId: string; modelProviderConfigurationId: string; geoGapActionId?: string; contentTask?: ContentTaskInput; queryEvidenceSelection?: QueryEvidenceSelectionInput }) { return request<ContentPlan>('/api/workspaces/' + session.workspaceId + '/content-opportunities/' + diagnosisId + '/ai-plan', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listContentStrategies(session: WorkspaceSession) { return request<{ strategies: ContentStrategy[] }>('/api/workspaces/' + session.workspaceId + '/content-strategies', { session }) }
export function createContentStrategy(session: WorkspaceSession, input: { logicalKey: string; diagnosisId: string; marketPackId: string; targetQueryIds: string[]; channels: string[]; title: string; objective: string; strategy: ContentStrategy['strategy'] }) { return request<{ strategy: ContentStrategy }>('/api/workspaces/' + session.workspaceId + '/content-strategies', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function reviewContentStrategy(session: WorkspaceSession, strategyId: string, status: 'approved'|'rejected', reviewComment: string) { return request<{ strategy: ContentStrategy }>('/api/workspaces/' + session.workspaceId + '/content-strategies/' + strategyId + '/review', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status, reviewComment }) }) }
export function listContentBriefs(session: WorkspaceSession) { return request<{ briefs: ContentBrief[] }>('/api/workspaces/' + session.workspaceId + '/content-briefs', { session }) }
export function createContentBrief(session: WorkspaceSession, input: { logicalKey: string; diagnosisId: string; marketPackId: string; targetQueryIds: string[]; channel: string; contentType: 'website-page'|'faq'|'use-case'|'comparison-page'|'case-study'|'editorial'; title: string; strategyId?: string }) { return request<{ brief: ContentBrief }>('/api/workspaces/' + session.workspaceId + '/content-briefs', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function reviewContentBrief(session: WorkspaceSession, briefId: string, status: 'approved'|'rejected', reviewComment: string) { return request<{ brief: ContentBrief; geoGapAction?: GeoGapAction | null }>('/api/workspaces/' + session.workspaceId + '/content-briefs/' + briefId + '/review', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status, reviewComment }) }) }
export function listContentDrafts(session: WorkspaceSession) { return request<{ drafts: ContentDraft[] }>('/api/workspaces/' + session.workspaceId + '/content-drafts', { session }) }
export function getContentDraft(session: WorkspaceSession, draftId: string) { return request<{ draft: ContentDraft; claimValidations: DraftClaimValidation[]; approvedSnapshot: ApprovedContentSnapshot | null; aiInvocation: { modelIdentity?: string | null; promptTemplateVersion?: string } | null }>('/api/workspaces/' + session.workspaceId + '/content-drafts/' + draftId, { session }) }
export function generateContentDraft(session: WorkspaceSession, briefId: string, input: { logicalKey: string; title: string; modelProviderConfigurationId?: string; contentPromptProfileId?: string; templateOnly?: boolean; promptOverride?: string }) { return request<{ draft: ContentDraft; claimValidations: DraftClaimValidation[]; geoGapAction?: GeoGapAction | null; executionBoundary: string }>('/api/workspaces/' + session.workspaceId + '/content-briefs/' + briefId + '/drafts', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function resolveDraftClaim(session: WorkspaceSession, draftId: string, claimId: string, input: { status: 'supported'|'rejected'; evidenceRefs?: string[]; resolutionComment: string }) { return request<{ claim: DraftClaimValidation }>('/api/workspaces/' + session.workspaceId + '/content-drafts/' + draftId + '/claims/' + claimId + '/resolve', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function reviewContentDraft(session: WorkspaceSession, draftId: string, status: 'approved'|'rejected', reviewComment: string) { return request<{ draft: ContentDraft; geoGapAction?: GeoGapAction | null; approvedSnapshot: ApprovedContentSnapshot | null }>('/api/workspaces/' + session.workspaceId + '/content-drafts/' + draftId + '/review', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status, reviewComment }) }) }
export function updateContentDraft(session: WorkspaceSession, draftId: string, contentMarkdown: string) { return request<{ draft: ContentDraft; claimValidations: DraftClaimValidation[] }>('/api/workspaces/' + session.workspaceId + '/content-drafts/' + draftId, { method: 'PUT', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ contentMarkdown }) }) }
export function listContentPublications(session: WorkspaceSession) { return request<{ publications: ContentPublication[] }>('/api/workspaces/' + session.workspaceId + '/content-publications', { session }) }
export function registerContentPublication(session: WorkspaceSession, input: { approvedSnapshotId: string; channel: string; publishedUrl: string; publishedAt: string; proofArtifactId: string; targetQueryIds: string[]; notes?: string }) { return request<{ publication: ContentPublication }>('/api/workspaces/' + session.workspaceId + '/content-publications', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function scheduleContentPublicationRetest(session: WorkspaceSession, publicationId: string, input: { scheduledFor: string; cadence: 'once'|'weekly'|'monthly'; notes?: string }) { return request<{ publication: ContentPublication }>('/api/workspaces/' + session.workspaceId + '/content-publications/' + publicationId + '/retest', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function getContentPublicationObservation(session: WorkspaceSession, publicationId: string) { return request<{ observation: ContentPublicationObservation }>('/api/workspaces/' + session.workspaceId + '/content-publications/' + publicationId + '/observation', { session }) }

export type ProjectContentPrerequisite = { code: string; title: string; detail: string; destination: 'diagnostics'|'queryResearch'|'baseline'; actionLabel: string }
export type ProjectContentQuery = { id: string; question: string; intent?: string; priority?: string; market?: string; locale?: string; queryType?: string; journeyStage?: string }
export type ProjectContentFact = { id: string; statement: string; category?: string; sourceLabel?: string; sourceUrl?: string | null; reviewedAt?: string | null }
export type ProjectContentObservation = { taskId: string; platform: string; providerFamily?: string; observedAt?: string | null; reviewedAt?: string | null; answerUrl?: string | null; answerExcerpt: string; citations: string[] }
export type ProjectContentOpportunity = {
  id: string; type: 'brand-unmentioned'|'owned-source-gap'|'query-coverage-gap'; title: string; recommendation: string;
  queryScope: ProjectContentQuery[];
  source: { testRunId: string; querySetId: string; marketPack: string; locale: string; platforms: string[]; reviewedObservationCount: number };
  evidence: { approvedFacts: ProjectContentFact[]; observations: ProjectContentObservation[]; citations: Array<{ url: string; sourceType: 'owned'|'third-party'|'unknown' }> };
  limitations: string[]; sourceContext: Record<string, unknown>
}
export type ProjectContentOpportunityResponse = { project: BrandDiagnosticProjectSummary; opportunities: ProjectContentOpportunity[]; prerequisites: ProjectContentPrerequisite[] }
const projectContentPath = (session: WorkspaceSession, projectId: string, resource: string) => `/api/workspaces/${session.workspaceId}/projects/${projectId}/${resource}`
export function getProjectContentOpportunities(session: WorkspaceSession, projectId: string) { return request<ProjectContentOpportunityResponse>(projectContentPath(session, projectId, 'content-opportunities'), { session }) }
export type ContentQueryExpansionRow = { query: string; category?: string; intent?: string; cluster?: string }
export function expandProjectContentQueries(session: WorkspaceSession, projectId: string, input: { seeds: string[]; count?: number; providerConfigurationId: string; promptOverride?: string }) { return request<{ queries: ContentQueryExpansionRow[]; model: string; elapsedMs: number }>(projectContentPath(session, projectId, 'content-query-expansion'), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listProjectContentStrategies(session: WorkspaceSession, projectId: string) { return request<{ strategies: ContentStrategy[] }>(projectContentPath(session, projectId, 'content-strategies'), { session }) }
export function createProjectContentStrategy(session: WorkspaceSession, projectId: string, input: { opportunityId: string; logicalKey: string; title: string; objective: string; channels: string[]; autoApprove?: boolean }) { return request<{ strategy: ContentStrategy; boundary: string }>(projectContentPath(session, projectId, 'content-strategies'), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function reviewProjectContentStrategy(session: WorkspaceSession, projectId: string, strategyId: string, input: { status: 'approved'|'rejected'; reviewComment: string }) { return request<{ strategy: ContentStrategy }>(projectContentPath(session, projectId, `content-strategies/${strategyId}/review`), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listProjectContentBriefs(session: WorkspaceSession, projectId: string) { return request<{ briefs: ContentBrief[] }>(projectContentPath(session, projectId, 'content-briefs'), { session }) }
export function reviewProjectContentBrief(session: WorkspaceSession, projectId: string, briefId: string, input: { status: 'approved'|'rejected'; reviewComment: string }) { return request<{ brief: ContentBrief }>(projectContentPath(session, projectId, `content-briefs/${briefId}/review`), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function createProjectContentDraft(session: WorkspaceSession, projectId: string, briefId: string, input: { logicalKey: string; title: string; modelProviderConfigurationId?: string; contentPromptProfileId?: string; templateOnly?: boolean; promptOverride?: string }) { return request<{ draft: ContentDraft; claimValidations: DraftClaimValidation[]; aiInvocation: { id: string; status?: string; modelIdentity?: string | null }; executionBoundary: string }>(projectContentPath(session, projectId, `content-briefs/${briefId}/drafts`), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function getProjectContentDraft(session: WorkspaceSession, projectId: string, draftId: string) { return request<{ draft: ContentDraft; claimValidations: DraftClaimValidation[]; approvedSnapshot: ApprovedContentSnapshot | null; aiInvocation: { id: string; status?: string; modelIdentity?: string | null; promptTemplateVersion?: string; inputRefs?: string[]; outputRefs?: string[]; failureDetail?: string | null } | null }>(projectContentPath(session, projectId, `content-drafts/${draftId}`), { session }) }
export function getProjectContentDeliveryPackage(session: WorkspaceSession, projectId: string, draftId: string) { return request<{ deliveryPackage: ContentDeliveryPackage }>(projectContentPath(session, projectId, `content-drafts/${draftId}/delivery-package`), { session }) }
export function updateProjectContentDraft(session: WorkspaceSession, projectId: string, draftId: string, contentMarkdown: string) { return request<{ draft: ContentDraft; claimValidations: DraftClaimValidation[] }>(projectContentPath(session, projectId, `content-drafts/${draftId}`), { method: 'PUT', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ contentMarkdown }) }) }
export function saveProjectContentDraftQuality(session: WorkspaceSession, projectId: string, draftId: string, report: { duplicateScore: number; hallucinationRisk: number; keywordDensity: number; readabilityScore: number; semanticRelevanceScore: number; eeatScore: number; total: number; passed: boolean; issues: string[] }) { return request<{ draft: ContentDraft }>(projectContentPath(session, projectId, `content-drafts/${draftId}/quality`), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ qualityReport: report }) }) }
export function reviewProjectContentDraft(session: WorkspaceSession, projectId: string, draftId: string, input: { status: 'approved'|'rejected'; reviewComment: string }) { return request<{ draft: ContentDraft; approvedSnapshot?: ApprovedContentSnapshot | null }>(projectContentPath(session, projectId, `content-drafts/${draftId}/review`), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listProjectDraftClaims(session: WorkspaceSession, projectId: string, draftId: string) { return request<{ claimValidations: DraftClaimValidation[] }>(projectContentPath(session, projectId, `content-drafts/${draftId}/claims`), { session }) }
export function resolveProjectDraftClaim(session: WorkspaceSession, projectId: string, draftId: string, claimId: string, input: { status: 'supported'|'rejected'; evidenceRefs?: string[]; resolutionComment: string }) { return request<{ claim: DraftClaimValidation }>(projectContentPath(session, projectId, `content-drafts/${draftId}/claims/${claimId}/resolve`), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function createProjectContentBrief(session: WorkspaceSession, projectId: string, input: { strategyId: string; logicalKey: string; channel: string; contentType: 'website-page'|'faq'|'use-case'|'comparison-page'|'case-study'|'editorial'; title: string; autoApprove?: boolean }) { return request<{ brief: ContentBrief; boundary: string }>(projectContentPath(session, projectId, 'content-briefs'), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listProjectContentDrafts(session: WorkspaceSession, projectId: string) { return request<{ drafts: ContentDraft[] }>(projectContentPath(session, projectId, 'content-drafts'), { session }) }
export function listProjectContentPublications(session: WorkspaceSession, projectId: string) { return request<{ publications: ContentPublication[]; boundary: string }>(projectContentPath(session, projectId, 'content-publications'), { session }) }
export function registerProjectContentPublication(session: WorkspaceSession, projectId: string, input: { approvedSnapshotId: string; channel: string; publishedUrl: string; publishedAt: string; targetQueryIds: string[]; notes?: string; proof?: PublicationProofInput }) { return request<{ publication: ContentPublication; boundary: string }>(projectContentPath(session, projectId, 'content-publications'), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function scheduleProjectContentPublicationRetest(session: WorkspaceSession, projectId: string, publicationId: string, input: { scheduledFor: string; cadence: 'once'|'weekly'|'monthly'; notes?: string }) { return request<{ publication: ContentPublication; boundary: string }>(projectContentPath(session, projectId, `content-publications/${publicationId}/retest`), { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }


export type ProviderCredential = { configured: boolean; encryptionVersion: string; lastFour: string; createdAt: string; updatedAt: string }
export type ModelProviderTest = { status: 'unverified'|'verified'|'failed'; testedAt?: string | null; model?: string | null; latencyMs?: number | null; message?: string | null }
export type ModelProviderConfiguration = { id: string; providerId: string; market: 'CN'|'GLOBAL'; locale: string; collectionMode: 'controlled-manual'|'official-api'|'enterprise-gateway'|'mcp'; credentialReference?: string | null; status: 'configured'|'disabled'; version: number; execution?: { baseUrl: string; modelName: string; updatedAt: string; updatedBy: string } | null; credential?: ProviderCredential | null; test?: ModelProviderTest; executable?: boolean }
export function listModelProviders(session: WorkspaceSession) { return request<{ providers: ModelProviderConfiguration[]; collectionBoundary: string }>('/api/workspaces/' + session.workspaceId + '/model-providers', { session }) }
export function configureModelProvider(session: WorkspaceSession, input: { providerId: string; market: 'CN'|'GLOBAL'; locale: string; collectionMode: ModelProviderConfiguration['collectionMode']; status?: 'configured'|'disabled'; baseUrl?: string; modelName?: string; useForQueryGeneration?: boolean }) { return request<{ provider: ModelProviderConfiguration }>('/api/workspaces/' + session.workspaceId + '/model-providers', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function storeModelProviderCredential(session: WorkspaceSession, providerConfigurationId: string, apiKey: string) { return request<{ provider: ModelProviderConfiguration; persistence: string }>('/api/workspaces/' + session.workspaceId + '/model-providers/' + providerConfigurationId + '/credential', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ apiKey }) }) }
export function testModelProviderConnection(session: WorkspaceSession, providerConfigurationId: string) { return request<{ ok: boolean; model: string; elapsedMs: number; test: ModelProviderTest }>('/api/workspaces/' + session.workspaceId + '/model-providers/' + providerConfigurationId + '/test', { method: 'POST', session }) }
export type ProviderExecutionReadiness = { providerId: string; market: 'CN'|'GLOBAL'; locale: string; state: 'manual-fallback'|'needs-connection'|'needs-credential'|'adapter-pending'; label: string; collectionMode?: ModelProviderConfiguration['collectionMode']; providerConfigurationId?: string; credentialConfigured: boolean; nextAction: string }
export function getProviderExecutionReadiness(session: WorkspaceSession, marketPackId: string) { return request<{ readiness: ProviderExecutionReadiness[]; executionBoundary: string }>('/api/workspaces/' + session.workspaceId + '/market-packs/' + marketPackId + '/execution-readiness', { session }) }

export type BatchImportTemplateItem = { observationId: string; queryId: string; queryText: string; providerId: string; locale: string; collectionMode: 'controlled-manual'; status: string; modelIdentity: string; sourceRef: string; collectedAt: string; citations: Array<{ url: string; kind: 'owned'|'third-party'|'unknown' }>; rawAnswer: string }
export type BatchImportTemplate = { schemaVersion: 'geo-controlled-manual-batch-v1'; assessmentRunId: string; label: string; locale: string; collectionMode: 'controlled-manual'; generatedAt: string; items: BatchImportTemplateItem[]; instructions: string[] }
export type BatchObservationImport = Pick<BatchImportTemplateItem, 'queryId'|'providerId'|'modelIdentity'|'sourceRef'|'collectedAt'|'citations'|'rawAnswer'>
export function getBatchImportTemplate(session: WorkspaceSession, assessmentRunId: string) { return request<{ template: BatchImportTemplate }>('/api/workspaces/' + session.workspaceId + '/assessment-runs/' + assessmentRunId + '/batch-import-template', { session }) }
export function importObservationBatch(session: WorkspaceSession, assessmentRunId: string, rows: BatchObservationImport[]) { return request<{ imported: Observation[]; skipped: Array<{ queryId: string; providerId: string; reason: string }>; run: AssessmentRun; collectionMode: 'controlled-manual' }>('/api/workspaces/' + session.workspaceId + '/assessment-runs/' + assessmentRunId + '/observations/batch-import', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ collectionMode: 'controlled-manual', rows }) }) }

export type BrandDiagnosticProjectSummary = {
  id: string; name: string; brandName: string; website: string; markets: string[]; locales: string[]; audiences: string[]; objective: string; ownerId: string; deliveryDate?: string | null; status: string; updatedAt: string; activeRealSurfaceTestRunId?: string | null;
  factSummary: { approved: number; candidates: number }; blockers: Array<{ code: string; message: string; tab: string }>;
  queryScope?: { expectedCount: number; datasetVersionLabel: string } | null; collectionPlan?: { collectionMode: string; providers: string[]; status: string } | null;
  baseline?: { id: string; version: number; createdAt: string } | null; coverage: { expected: number; imported: number; rate: number | null; status: string }; nextAction: { label: string; tab: string }
}
export type BrandDiagnosticFact = { id: string; statement: string; category: string; appliesToMarkets: string[]; sourceLabel: string; sourceUrl?: string | null; status: 'candidate'|'approved'|'rejected'; isProhibitedClaim: boolean; reviewNote?: string | null; reviewedAt?: string | null; reviewedBy?: string | null; createdAt: string }
export type BrandDiagnosticScope = { id: string; journeys: string[]; queryTypes: string[]; markets: string[]; locales: string[]; competitorSeeds: string[]; expectedCount: number; datasetVersionLabel: string; updatedAt: string }
export type BrandDiagnosticCollectionPlan = { id: string; providers: string[]; collectionMode: 'controlled-manual'|'official-api'|'enterprise-gateway'|'mcp'; frequency: string; failurePolicy: string; status: string; updatedAt: string }
export type BrandDiagnosticBrief = { id: string; caseId: string; version: number; goal: 'baseline'; category: string; marketPacks: Array<'CN'|'US'>; intents: string[]; evidenceUrls: string[]; competitors: string[]; executionPreference: 'ai-assisted'|'controlled-manual'; createdAt: string; updatedAt: string; updatedBy: string }
export type BrandDiagnosticDetail = { project: Omit<BrandDiagnosticProjectSummary, 'factSummary'|'blockers'|'queryScope'|'collectionPlan'|'baseline'|'coverage'|'nextAction'>; facts: BrandDiagnosticFact[]; queryScope?: BrandDiagnosticScope | null; collectionPlan?: BrandDiagnosticCollectionPlan | null; brief?: BrandDiagnosticBrief | null; launchPlan?: ActionableLaunchPlan | null; baseline?: { id: string; version: number; snapshot: Record<string, unknown>; createdAt: string; createdBy: string } | null; activities: Array<{ id: string; type: string; detail: string; createdAt: string; actorId: string }>; recommendations: Array<{ id: string; title: string; destination: string; rationale: string; evidenceState: string; createdAt: string }>; readiness: { blockers: Array<{ code: string; message: string; tab: string }>; approvedFacts: number; candidateFacts: number; hasScope: boolean; hasPlan: boolean; baselineReady: boolean }; coverage: { expected: number; imported: number; rate: number | null; status: string; message: string }; collectionBoundary: string }
export type BrandDiagnosticInput = { name: string; brandName: string; website: string; markets: string[]; locales: string[]; audiences: string[]; objective: string; ownerId?: string; deliveryDate?: string | null }
export function listBrandDiagnostics(session: WorkspaceSession) { return request<{ projects: BrandDiagnosticProjectSummary[] }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics', { session }) }
export function getBrandDiagnostic(session: WorkspaceSession, caseId: string) { return request<{ project: BrandDiagnosticDetail }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId, { session }) }
export function createBrandDiagnostic(session: WorkspaceSession, input: BrandDiagnosticInput) { return request<{ project: BrandDiagnosticDetail }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function updateBrandDiagnostic(session: WorkspaceSession, caseId: string, input: Partial<BrandDiagnosticInput>) { return request<{ project: BrandDiagnosticDetail }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId, { method: 'PATCH', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function deleteBrandDiagnostic(session: WorkspaceSession, caseId: string, confirmationName: string) { return request<{ deleted: { id: string; name: string } }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId, { method: 'DELETE', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ confirmationName }) }) }
export function createBrandDiagnosticFact(session: WorkspaceSession, caseId: string, input: Omit<BrandDiagnosticFact, 'id'|'createdAt'|'reviewedAt'|'reviewedBy'|'reviewNote'>) { return request<{ fact: BrandDiagnosticFact }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId + '/facts', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function reviewBrandDiagnosticFact(session: WorkspaceSession, caseId: string, factId: string, status: 'approved'|'rejected', reviewNote = '') { return request<{ fact: BrandDiagnosticFact }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId + '/facts/' + factId + '/review', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status, reviewNote }) }) }
export function saveBrandDiagnosticScope(session: WorkspaceSession, caseId: string, input: Omit<BrandDiagnosticScope, 'id'|'updatedAt'>) { return request<{ queryScope: BrandDiagnosticScope }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId + '/query-scope', { method: 'PUT', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function saveBrandDiagnosticCollectionPlan(session: WorkspaceSession, caseId: string, input: Omit<BrandDiagnosticCollectionPlan, 'id'|'updatedAt'|'status'>) { return request<{ collectionPlan: BrandDiagnosticCollectionPlan }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId + '/collection-plan', { method: 'PUT', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function freezeBrandDiagnosticBaseline(session: WorkspaceSession, caseId: string) { return request<{ project: BrandDiagnosticDetail }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId + '/freeze-baseline', { method: 'POST', session }) }
export type ActionableBrandDiagnosticInput = { brandName: string; website: string; category: string; marketPacks: Array<'CN'|'US'>; audiences: string[]; intents: string[]; evidenceUrls?: string[]; competitors?: string[]; executionPreference: 'ai-assisted'|'controlled-manual' }
export type ActionableLaunchPlan = { id: string; state: 'ready'|'manual-ready'|'configuration-required'; briefVersion?: number; brief?: { version: number; goal: string; category: string; marketPacks: Array<'CN'|'US'>; intents: string[]; evidenceUrls: string[]; competitors: string[]; executionPreference: 'ai-assisted'|'controlled-manual' }; queryResearch: { intents: string[]; estimatedCandidateCount: number; rationale: string }; evidence: { ownedSourceCount: number; taskCount: number; rationale: string }; testing: { providers: string[]; plannedObservations: number; channels: string[]; collectionMode: string }; competitors: { seeds: string[]; taskCount: number; rationale?: string }; readiness: { title: string; detail: string; nextAction: string }; createdAt?: string; createdBy?: string }
export function launchActionableBrandDiagnostic(session: WorkspaceSession, input: ActionableBrandDiagnosticInput) { return request<{ project: BrandDiagnosticDetail; launchPlan: ActionableLaunchPlan }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/launch', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function updateActionableBrandDiagnostic(session: WorkspaceSession, caseId: string, input: ActionableBrandDiagnosticInput) { return request<{ project: BrandDiagnosticDetail; launchPlan: ActionableLaunchPlan }>('/api/workspaces/' + session.workspaceId + '/brand-diagnostics/' + caseId + '/brief', { method: 'PUT', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }

export type QueryGenerationPrompt = { id: string; workspaceId: string; name: string; template: string; version: number; status: 'active'|'archived'; createdAt: string; createdBy: string; updatedAt: string; updatedBy: string }
export type QueryGenerationSettings = { prompt: QueryGenerationPrompt; providers: ModelProviderConfiguration[]; promptHistory?: QueryGenerationPrompt[] }
export function getQueryGenerationSettings(session: WorkspaceSession) { return request<QueryGenerationSettings>('/api/workspaces/' + session.workspaceId + '/query-generation-settings', { session }) }
export function updateQueryGenerationPrompt(session: WorkspaceSession, input: { name?: string; template: string }) { return request<{ prompt: QueryGenerationPrompt }>('/api/workspaces/' + session.workspaceId + '/query-generation-settings', { method: 'PUT', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listQueryGenerationPromptHistory(session: WorkspaceSession) { return request<{ prompts: QueryGenerationPrompt[] }>('/api/workspaces/' + session.workspaceId + '/query-generation-settings/prompts', { session }) }
export function restoreQueryGenerationPrompt(session: WorkspaceSession, promptId: string) { return request<{ prompt: QueryGenerationPrompt }>('/api/workspaces/' + session.workspaceId + '/query-generation-settings/prompts/' + promptId + '/restore', { method: 'POST', session }) }
export function optimizeQueryGenerationPrompt(session: WorkspaceSession, input: { providerConfigurationId: string; goal: string; name?: string; template: string }) { return request<{ suggestion: string; model: string; elapsedMs: number; providerConfigurationId: string }>('/api/workspaces/' + session.workspaceId + '/query-generation-settings/optimize', { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export type CompetitorIntelligenceProfile = {
  id: string; workspaceId: string; name: string; selfBrandName: string; industry: string; productCategory: string; market: string;
  audiences: string[]; competitors: string[]; dimensions: string[]; rules: Record<string, unknown>; status: 'active'|'archived';
  createdAt: string; createdBy: string; updatedAt: string; updatedBy: string;
}
export type CompetitorAnalysisAgentType = 'answer-extraction'|'link-classification'|'page-structure'|'insight-synthesis'
export type CompetitorAnalysisPrompt = { id: string; workspaceId: string; profileId: string; agentType: CompetitorAnalysisAgentType; name: string; template: string; version: number; status: 'active'|'archived'; createdAt: string; createdBy: string; updatedAt: string; updatedBy: string }
export type CompetitorEvidence = { id: string; taskId: string; testRunId: string; testRunName: string; taskState: 'submitted'|'needs_revision'|'reviewed'; platform: string; providerFamily: string; question: string; platformLabel: string; rawAnswer: string; citations: string[]; answerUrl?: string | null; captureReference?: string | null; observedAt: string; reviewedAt?: string | null; captureMetadata: Record<string, unknown>; collectionMethod?: string | null; answerCitationCount: number; platformSearchSourceCount: number }
export type CompetitorEvidenceOverview = { capturedCount: number; approvedCount: number; approvedEvidenceCount: number; pendingReviewCount: number; rawAnswerCount: number; answerCitationCount: number; platformSearchSourceCount: number; platforms: Array<{ platformLabel: string; capturedCount: number; approvedCount: number; rawAnswerCount: number; answerCitationCount: number; platformSearchSourceCount: number; platforms: string[] }>; testRuns: Array<{ testRunId: string; testRunName: string; capturedCount: number; approvedCount: number; rawAnswerCount: number; answerCitationCount: number; platformSearchSourceCount: number; platforms: string[] }> }
export type CompetitorEvidenceAnalysis = { id: string; workspaceId: string; profileId: string; observationId: string; observationIds: string[]; scopeType: 'single-observation'|'baseline-cohort'|'query-cohort'; testRunId?: string | null; evidenceSummary: { recordCount?: number; approvedRecordCount?: number; capturedUnreviewedRecordCount?: number; platforms?: string[]; testRunName?: string | null; queryGroupId?: string | null; query?: string | null; selectedObservationId?: string | null; linkedPageAnalysisCount?: number; kind?: string; candidateId?: string; requestedUrl?: string; finalUrl?: string; title?: string; httpStatus?: number; contentType?: string; sourceTypes?: string[]; evidenceStates?: string[]; occurrenceCount?: number; approvedOccurrenceCount?: number; capturedOccurrenceCount?: number; queries?: string[] }; agentType: CompetitorAnalysisAgentType; state: 'running'|'succeeded'|'failed'; promptId?: string | null; promptVersion?: number | null; providerConfigurationId?: string | null; modelName?: string | null; inputHash: string; result: Record<string, unknown>; errorMessage?: string | null; startedAt: string; completedAt?: string | null; createdBy: string }
export type CompetitorQueryObservation = { observationId: string; taskId: string; platformLabel: string; platform: string; testRunId: string; testRunName: string; evidenceState: 'approved'|'captured'; approvalEligible: boolean; rawAnswerLength: number; answerPreview: string; linkCount: number; observedAt: string }
export type CompetitorQueryGroup = { id: string; question: string; observationCount: number; approvedCount: number; pendingCount: number; approvableCount: number; linkCount: number; platforms: string[]; testRuns: Array<{ testRunId: string; testRunName: string }>; observations: CompetitorQueryObservation[]; lastObservedAt: string }
export type CompetitorLinkOccurrence = { observationId: string; testRunId: string; testRunName: string; platform: string; query: string; queryGroupId: string; observedAt: string; sourceType: string; evidenceState: 'approved'|'captured'; title: string; position: number }
export type CompetitorLinkCandidate = { id: string; url: string; domain: string; title: string; sourceTypes: string[]; evidenceStates: Array<'approved'|'captured'>; observationIds: string[]; testRuns: Array<{ testRunId: string; testRunName: string }>; platforms: string[]; queries: string[]; queryGroups: Array<{ id: string; question: string }>; occurrences: CompetitorLinkOccurrence[]; occurrenceCount: number; approvedOccurrenceCount: number; capturedOccurrenceCount: number; firstObservedAt: string; lastObservedAt: string; directlyOpenable: boolean }
export type GeoGapActionType = 'improve-owned-page'|'create-comparison-page'|'create-faq'|'create-case-study'|'source-research'
export type GeoGapActionStatus = 'draft'|'in-progress'|'completed'|'dismissed'
export type GeoGapAction = {
  id: string; workspaceId: string; queryGroupId: string; analysisId: string; actionKey: string;
  priority: 'high'|'medium'|'low'; status: GeoGapActionStatus; actionType: GeoGapActionType; title: string; gapSummary: string;
  evidenceSnapshot: { query?: string; queryGroupId?: string; approvedAnswerCount?: number; platforms?: string[]; observationIds?: string[]; visibleSources?: Array<{ domain: string; title: string; url: string; occurrences: number; platforms: string[] }>; analysisId?: string; analysisCompletedAt?: string | null };
  recommendation: { source?: string; recommendedAction?: string; recommendedFormat?: string; expectedSignal?: string; evidenceIds?: string[]; contentRequirements?: string[] };
  limitations: string[];
  contentBrief: { title?: string; status?: string; objective?: string; recommendedFormat?: string; gapSummary?: string; contentRequirements?: string[]; prohibitedClaims?: string[]; createdAt?: string } | null;
  contentBriefCreatedAt?: string | null;
  contentWorkflow: { stage: 'action-ready'|'brief-ready'|'brief-needs-review'|'brief-approved'|'brief-rejected'|'draft-needs-review'|'ready-to-publish'|'draft-rejected'|'published-awaiting-retest'|'retest-scheduled'|string; contentStrategyId?: string | null; contentBriefId?: string | null; contentDraftId?: string | null; contentPublicationId?: string | null };
  retestPlan: { status?: string; cadence?: string; scheduledFor?: string; trigger?: string; comparisonScope?: string; publicationId?: string; createdAt?: string } | null;
  retestPlanCreatedAt?: string | null;
  createdAt: string; createdBy: string; updatedAt: string; updatedBy: string;
}
export type CompetitorIntelligenceProfileInput = Pick<CompetitorIntelligenceProfile, 'name'|'selfBrandName'|'industry'|'productCategory'|'market'|'audiences'|'competitors'|'dimensions'|'rules'>
export function listCompetitorIntelligenceProfiles(session: WorkspaceSession) { return request<{ profiles: CompetitorIntelligenceProfile[] }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence`, { session }) }
export function ensureDefaultCompetitorIntelligenceProfile(session: WorkspaceSession) { return request<{ profile: CompetitorIntelligenceProfile }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/default-profile`, { method: 'POST', session }) }
export function listCompetitorQueryGroups(session: WorkspaceSession, caseId?: string | null) { const query = caseId ? `?caseId=${encodeURIComponent(caseId)}` : ''; return request<{ queryGroups: CompetitorQueryGroup[] }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/query-groups${query}`, { session }) }
export function approveCompetitorQueryGroupEvidence(session: WorkspaceSession, queryGroupId: string, input: { observationId?: string; reviewNote?: string } = {}) { return request<{ approval: { queryGroupId: string; observationId: string | null; approvedCount: number; skippedCount: number; queryGroup: CompetitorQueryGroup | null } }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/query-groups/${queryGroupId}`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listGeoGapActions(session: WorkspaceSession, queryGroupId: string) { return request<{ actions: GeoGapAction[] }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/query-groups/${queryGroupId}/gap-actions`, { session }) }
export function generateGeoGapActions(session: WorkspaceSession, queryGroupId: string, analysisId: string) { return request<{ actions: GeoGapAction[] }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/query-groups/${queryGroupId}/gap-actions`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ analysisId }) }) }
export function updateGeoGapAction(session: WorkspaceSession, actionId: string, status: GeoGapActionStatus) { return request<{ action: GeoGapAction }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/gap-actions/${actionId}`, { method: 'PATCH', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) }) }
export function createGeoGapActionContentBrief(session: WorkspaceSession, actionId: string) { return request<{ action: GeoGapAction }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/gap-actions/${actionId}/content-brief`, { method: 'POST', session }) }
export function createGeoGapActionRetestPlan(session: WorkspaceSession, actionId: string, scheduledFor?: string) { return request<{ action: GeoGapAction }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/gap-actions/${actionId}/retest-plan`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(scheduledFor ? { scheduledFor } : {}) }) }
export function listCompetitorLinkCandidates(session: WorkspaceSession, scope: { queryGroupId?: string; observationId?: string } = {}) {
  const params = new URLSearchParams()
  if (scope.queryGroupId) params.set('queryGroupId', scope.queryGroupId)
  if (scope.observationId) params.set('observationId', scope.observationId)
  const suffix = params.size ? `?${params.toString()}` : ''
  return request<{ candidates: CompetitorLinkCandidate[] }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/link-candidates${suffix}`, { session })
}
export function createCompetitorIntelligenceProfile(session: WorkspaceSession, input: CompetitorIntelligenceProfileInput) { return request<{ profile: CompetitorIntelligenceProfile }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function updateCompetitorIntelligenceProfile(session: WorkspaceSession, profileId: string, input: Partial<CompetitorIntelligenceProfileInput>) { return request<{ profile: CompetitorIntelligenceProfile }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/profiles/${profileId}`, { method: 'PATCH', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listCompetitorAnalysisPrompts(session: WorkspaceSession, profileId: string) { return request<{ prompts: CompetitorAnalysisPrompt[] }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/profiles/${profileId}/prompts`, { session }) }
export function updateCompetitorAnalysisPrompt(session: WorkspaceSession, profileId: string, input: { agentType: CompetitorAnalysisAgentType; name: string; template: string }) { return request<{ prompt: CompetitorAnalysisPrompt }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/profiles/${profileId}/prompts`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function restoreCompetitorAnalysisPrompt(session: WorkspaceSession, profileId: string, promptId: string, agentType: CompetitorAnalysisAgentType) { return request<{ prompt: CompetitorAnalysisPrompt }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/profiles/${profileId}/prompts/${promptId}/restore?agentType=${encodeURIComponent(agentType)}`, { method: 'POST', session }) }
export function listApprovedCompetitorEvidence(session: WorkspaceSession, profileId: string) { return request<{ evidence: CompetitorEvidence[]; pendingEvidence: CompetitorEvidence[]; overview: CompetitorEvidenceOverview }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/profiles/${profileId}/evidence`, { session }) }
export function listCompetitorEvidenceAnalyses(session: WorkspaceSession, profileId: string) { return request<{ analyses: CompetitorEvidenceAnalysis[] }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/profiles/${profileId}/analyses`, { session }) }
export function createCompetitorEvidenceAnalysis(session: WorkspaceSession, profileId: string, input: { scopeType?: 'single-observation'|'baseline-cohort'|'query-cohort'; observationId?: string; testRunId?: string; queryGroupId?: string; providerConfigurationId: string; agentType: CompetitorAnalysisAgentType }) { return request<{ analysis: CompetitorEvidenceAnalysis }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/profiles/${profileId}/analyses`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function createCompetitorLinkPageAnalysis(session: WorkspaceSession, profileId: string, input: { candidateId: string; providerConfigurationId: string; queryGroupId?: string; observationId?: string }) { return request<{ analysis: CompetitorEvidenceAnalysis }>(`/api/workspaces/${session.workspaceId}/competitor-intelligence/profiles/${profileId}/link-analyses`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }

export type QueryResearchMetadata = { queryType?: string; journeyStage?: string; targetEntityType?: string; targetEntities?: string[]; audienceSegment?: string; scenario?: string; sourceType?: string; sourceReference?: string; queryGroup?: string; isBaseline?: boolean }
export type BaselineSeedQuery = { id: string; workspaceId: string; querySetId: string; sequence: number; question: string; intent: string; rationale: string; market: string; locale: string; priority: 'high'|'medium'|'low'; status: 'draft'|'approved'|'excluded'; provenance: string; queryType: string; journeyStage: string; targetEntityType: string; targetEntities: string[]; audienceSegment?: string | null; scenario?: string | null; sourceType: string; sourceReference?: string | null; queryGroup?: string | null; isBaseline: boolean; createdAt: string; updatedAt: string }
export type BaselineCoverageBreakdown = string[] | Record<string, number>
export type QueryCoverageTargetMap = Record<string, number>
export type QueryCoverageCell = { key: string; queryType: string; journeyStage: string; current: number; target: number; gap: number; state: 'covered'|'gap'|'not-applicable'; queryIds: string[] }
export type QueryCoverageMap = { queryTypes: string[]; journeys: string[]; cells: QueryCoverageCell[]; summary: { applicableCells: number; coveredCells: number; gapCells: number; missingQueries: number } }
export type BaselineQuerySet = { id: string; workspaceId: string; caseId: string; name: string; marketPack: 'CN'|'US'; locale: string; generationMode: 'template'|'llm-assisted'|'manual'|'revision'; status: 'draft'|'approved'|'superseded'; lifecycleStatus: 'draft'|'in_review'|'ready_for_test'|'locked_for_baseline'|'superseded'; version: number; parentQuerySetId?: string | null; publishedAt?: string | null; publishedBy?: string | null; lockedAt?: string | null; lockedBy?: string | null; archivedAt?: string | null; archivedBy?: string | null; isActive: boolean; coverageTargets: QueryCoverageTargetMap; coverage: QueryCoverageMap; health: { total: number; approved: number; draft: number; excluded: number; queryTypes: BaselineCoverageBreakdown; journeys: BaselineCoverageBreakdown; targets: BaselineCoverageBreakdown; recommendations: string[] }; queries: BaselineSeedQuery[]; createdAt: string; createdBy: string; updatedAt: string; updatedBy: string }
export type RealSurfaceObservation = { id: string; rawAnswer: string; citations: string[]; answerUrl?: string | null; captureReference?: string | null; freshSession: boolean; searchEnabled: boolean; platformLabel: string; platformVersion?: string | null; observedAt: string; submittedBy: string; submittedAt: string; reviewedBy?: string | null; reviewedAt?: string | null; reviewerNote?: string | null; collectionMethod?: 'controlled-manual'|'browser-agent'; browserAgentId?: string | null; adapterId?: string | null; adapterVersion?: string | null; evidenceHash?: string | null; captureMetadata?: Record<string, unknown> | null }
export type RealSurfaceTask = { id: string; workspaceId: string; testRunId: string; seedQueryId: string; platform: string; providerFamily: string; state: 'unassigned'|'claimed'|'submitted'|'needs_revision'|'reviewed'|'failed'|'skipped'; executionMode?: 'controlled-manual'|'browser-agent'; browserAgentId?: string | null; agentState?: 'manual'|'queued'|'running'|'needs-human'|'captured'|'failed'; agentStateReason?: string | null; adapterId?: string | null; adapterVersion?: string | null; operatorId?: string | null; claimedAt?: string | null; submittedAt?: string | null; updatedAt?: string | null; failureReason?: string | null; attemptNumber: number; question: string; intent: string; rationale: string; observation?: RealSurfaceObservation | null }
export type BrowserAgent = { id: string; workspaceId: string; label: string; status: 'pending'|'online'|'needs_login'|'attention'|'revoked'|'offline'; platforms: string[]; adapters: Array<{id: string; version: string; platform: string}>; activeTestRunId?: string | null; enrolledAt?: string | null; lastSeenAt?: string | null; lastError?: string | null; createdAt: string; createdBy: string }
export type BrowserAgentEnrollment = { agent: BrowserAgent; enrollmentCode: string; expiresAt: string }
export type BrowserAgentStartRequest = { id: string; workspaceId: string; agentId: string; testRunId: string; platform: string; status: 'requested'|'acknowledged'|'launching-browser'|'waiting-login'|'running'|'completed'|'failed'|'cancelled'|'expired'; requestedBy: string; requestedAt: string; acknowledgedAt?: string | null; expiresAt: string; updatedAt: string; failureCode?: string | null; failureReason?: string | null; cancelledAt?: string | null; completedAt?: string | null }
export type RealSurfaceTestRun = { id: string; workspaceId: string; caseId: string; querySetId: string; name: string; marketPack: 'CN'|'US'; locale: string; collectionMode: 'controlled-manual'; executionMode?: 'controlled-manual'|'browser-agent'; browserAgentId?: string | null; state: 'draft'|'active'|'collecting'|'ready_for_review'|'baseline_ready'|'closed'; instructions: string; createdAt: string; createdBy: string; updatedAt: string; updatedBy: string; tasks: RealSurfaceTask[]; startRequests?: BrowserAgentStartRequest[]; progress: { total: number; byState: Record<string, number>; state: string } }
export function listBaselineQuerySets(session: WorkspaceSession, caseId: string) { return request<{ querySets: BaselineQuerySet[] }>(`/api/workspaces/${session.workspaceId}/brand-diagnostics/${caseId}/baseline-query-sets`, { session }) }
export function generateBaselineQuerySet(session: WorkspaceSession, caseId: string, input: { marketPack: 'CN'|'US'; count: number; generator?: 'llm'|'template'; keywords?: string[]; intents?: string[]; providerConfigurationId?: string | null; promptId?: string | null; querySetId?: string | null; coverageCell?: { queryType: string; journeyStage: string } | null }) { return request<{ querySet: BaselineQuerySet; generation?: { mode: string; providerId?: string; model?: string; promptVersion?: number; label?: string; elapsedMs?: number; timeoutMs?: number; providerRequestId?: string | null } }>(`/api/workspaces/${session.workspaceId}/brand-diagnostics/${caseId}/baseline-query-sets/generate`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export type ManualBaselineSeedQueryInput = { question: string; intent: string; rationale: string; priority: 'high'|'medium'|'low' } & QueryResearchMetadata
export function createManualBaselineQuerySet(session: WorkspaceSession, caseId: string, input: { name: string; marketPack: 'CN'|'US' } & ManualBaselineSeedQueryInput) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/brand-diagnostics/${caseId}/baseline-query-sets`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function archiveBaselineQuerySet(session: WorkspaceSession, querySetId: string) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}/archive`, { method: 'POST', session }) }
export function restoreBaselineQuerySet(session: WorkspaceSession, querySetId: string) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}/restore`, { method: 'POST', session }) }
export function activateBaselineQuerySet(session: WorkspaceSession, querySetId: string) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}/activate`, { method: 'POST', session }) }
export function deleteUnusedBaselineQuerySet(session: WorkspaceSession, querySetId: string, confirmation: string) { return request<{ deleted: { id: string; caseId: string } }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}`, { method: 'DELETE', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ confirmation }) }) }
export function publishBaselineQuerySet(session: WorkspaceSession, querySetId: string) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}/publish`, { method: 'POST', session }) }
export function createBaselineQuerySetRevision(session: WorkspaceSession, querySetId: string) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}/revision`, { method: 'POST', session }) }
export function updateBaselineQueryCoverageTargets(session: WorkspaceSession, querySetId: string, targets: QueryCoverageTargetMap) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}/coverage-targets`, { method: 'PATCH', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ targets }) }) }
export function updateBaselineSeedQuery(session: WorkspaceSession, querySetId: string, queryId: string, input: Partial<Pick<BaselineSeedQuery, 'question'|'intent'|'priority'|'rationale'|'status'> & QueryResearchMetadata>) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}/queries/${queryId}`, { method: 'PATCH', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function createManualBaselineSeedQuery(session: WorkspaceSession, querySetId: string, input: ManualBaselineSeedQueryInput) { return request<{ querySet: BaselineQuerySet }>(`/api/workspaces/${session.workspaceId}/baseline-query-sets/${querySetId}/queries`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listBrowserAgents(session: WorkspaceSession) { return request<{ agents: BrowserAgent[] }>(`/api/workspaces/${session.workspaceId}/browser-agents`, { session }) }
export function createBrowserAgentEnrollment(session: WorkspaceSession, input: { label: string; platforms: string[] }) { return request<BrowserAgentEnrollment>(`/api/workspaces/${session.workspaceId}/browser-agents/enrollments`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function revokeBrowserAgent(session: WorkspaceSession, agentId: string) { return request<{ agent: BrowserAgent }>(`/api/workspaces/${session.workspaceId}/browser-agents/${agentId}/revoke`, { method: 'POST', session }) }
export function createRealSurfaceTestRun(session: WorkspaceSession, caseId: string, input: { querySetId: string; marketPack: 'CN'|'US'; platforms: string[]; browserAgentId?: string | null; name?: string; requestKey?: string }) { return request<{ testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/brand-diagnostics/${caseId}/real-surface-test-runs`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function listRealSurfaceTestRuns(session: WorkspaceSession, caseId: string) { return request<{ testRuns: RealSurfaceTestRun[] }>(`/api/workspaces/${session.workspaceId}/brand-diagnostics/${caseId}/real-surface-test-runs?view=history`, { session }) }
export function getActiveRealSurfaceTestRun(session: WorkspaceSession, caseId: string) { return request<{ testRun: RealSurfaceTestRun | null }>(`/api/workspaces/${session.workspaceId}/brand-diagnostics/${caseId}/real-surface-test-runs`, { session }) }
/** @deprecated The route now resolves the project's active formal test source. */
export const getLatestRealSurfaceTestRun = getActiveRealSurfaceTestRun
export function getRealSurfaceTestRun(session: WorkspaceSession, testRunId: string) { return request<{ testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}`, { session }) }
export function appendRealSurfaceTestRunPlatforms(session: WorkspaceSession, testRunId: string, input: { platforms: string[]; browserAgentId: string | null }) { return request<{ testRun: RealSurfaceTestRun; addedPlatforms: string[] }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/platforms`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function enableRealSurfacePlatformBrowserAgent(session: WorkspaceSession, testRunId: string, input: { platform: string; browserAgentId: string }) { return request<{ testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/platforms/browser-agent`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function startBrowserAgentBatch(session: WorkspaceSession, testRunId: string, input: { browserAgentId: string; platform: string; forceRestart?: boolean }) { return request<{ startRequest: BrowserAgentStartRequest; testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/browser-agent-start`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function resumeBrowserAgentPlatform(session: WorkspaceSession, testRunId: string, input: { browserAgentId: string; platform: string }) { return request<{ testRun: RealSurfaceTestRun; resumedCount: number; resumedTaskIds: string[]; staleCount: number; reboundQueuedCount: number; reboundQueuedTaskIds: string[]; alreadyQueuedCount: number; activeCount: number; remainingCount: number; preservedCount: number }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/browser-agent-resume`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function cancelBrowserAgentBatchStart(session: WorkspaceSession, testRunId: string, startRequestId: string) { return request<{ startRequest: BrowserAgentStartRequest; testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/browser-agent-start/cancel`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ startRequestId }) }) }
export function claimRealSurfaceTask(session: WorkspaceSession, testRunId: string, taskId: string) { return request<{ testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/tasks/${taskId}/claim`, { method: 'POST', session }) }
export function retryRealSurfaceTaskWithBrowserAgent(session: WorkspaceSession, testRunId: string, taskId: string, browserAgentId: string) { return request<{ testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/tasks/${taskId}/retry-browser-agent`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ browserAgentId }) }) }
export function submitRealSurfaceObservation(session: WorkspaceSession, testRunId: string, taskId: string, input: { rawAnswer: string; citations: string[]; answerUrl?: string; captureReference?: string; freshSession: boolean; searchEnabled: boolean; platformVersion?: string; observedAt: string }) { return request<{ testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/tasks/${taskId}/observation`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function reviewRealSurfaceObservation(session: WorkspaceSession, testRunId: string, taskId: string, status: 'approved'|'needs_revision', reviewNote = '') { return request<{ testRun: RealSurfaceTestRun }>(`/api/workspaces/${session.workspaceId}/real-surface-test-runs/${testRunId}/tasks/${taskId}/review`, { method: 'POST', session, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status, reviewNote }) }) }








