import { useMemo, useState } from 'react'
import {
  Activity, ArrowUpRight, BarChart3, BellRing, BookOpenCheck, CheckCircle2,
  ChevronRight, CircleAlert, ClipboardCheck, FileText, Gauge, Globe2, LineChart,
  Link2, Menu, Network, PenLine, Radar, SearchCheck, ShieldCheck, Sparkles,
  Target, TrendingUp, Users, X,
} from 'lucide-react'

type DemoSection = 'overview' | 'queries' | 'baseline' | 'diagnosis' | 'research' | 'content' | 'assets' | 'monitoring' | 'reports'

type StaticDemoWorkspaceProps = { onExit: () => void }

const navItems: Array<{ id: DemoSection; label: string; meta: string; icon: typeof Gauge }> = [
  { id: 'overview', label: '工作台概览', meta: 'Overview', icon: Gauge },
  { id: 'queries', label: 'Query 研究', meta: '01', icon: SearchCheck },
  { id: 'baseline', label: '真实平台测试', meta: '02', icon: ClipboardCheck },
  { id: 'diagnosis', label: 'GEO 诊断与基线', meta: '03', icon: LineChart },
  { id: 'research', label: '行业与竞品研究', meta: '04', icon: Radar },
  { id: 'content', label: '内容策略与智能写作', meta: '05', icon: PenLine },
  { id: 'assets', label: '知识资产与发布准备', meta: '06', icon: Network },
  { id: 'reports', label: '报告中心', meta: '07', icon: FileText },
  { id: 'monitoring', label: '持续监控', meta: '运营', icon: BellRing },
]

const queries = [
  { text: '有哪些支持知识图谱、来源可追溯的 AI 知识库工具？', intent: '工具筛选', mention: '已提及', rate: '80%', source: '豆包 · DeepSeek · Kimi' },
  { text: '企业 RAG 知识库如何避免回答幻觉并保留来源？', intent: '问题解决', mention: '部分提及', rate: '60%', source: '元宝 · 千问' },
  { text: '适合出海 SaaS 团队的企业知识库应该怎么选？', intent: '购买决策', mention: '未提及', rate: '20%', source: 'DeepSeek · Kimi' },
]

const evidence = [
  ['CoreNote 官方产品页', 'corenote.cloud/product', '自有来源', '强'],
  ['知识图谱 AI 知识库选型指南', 'example.com/knowledge-guide', '第三方引用', '中'],
  ['RAG 应用实践与来源追溯', 'developer.example.com/rag', '行业来源', '中'],
]

export function StaticDemoWorkspace({ onExit }: StaticDemoWorkspaceProps) {
  const [section, setSection] = useState<DemoSection>('overview')
  const [navOpen, setNavOpen] = useState(false)
  const [notice, setNotice] = useState('')
  const active = navItems.find((item) => item.id === section) ?? navItems[0]
  const sectionTitle = useMemo(() => active.label, [active.label])
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400) }
  const go = (next: DemoSection) => { setSection(next); setNavOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }

  return <div className="static-demo-shell">
    <button className={navOpen ? 'static-demo-scrim show' : 'static-demo-scrim'} onClick={() => setNavOpen(false)} aria-label="关闭导航" />
    <aside className={navOpen ? 'static-demo-sidebar open' : 'static-demo-sidebar'}>
      <div className="static-demo-brand"><span><Sparkles size={17}/></span><div><strong>GEO Compass</strong><small>在线演示工作台</small></div><button className="static-demo-mobile-close" onClick={() => setNavOpen(false)} aria-label="关闭导航"><X size={17}/></button></div>
      <div className="static-demo-project"><span className="static-demo-project-dot"/><div><strong>CoreNote 示例项目</strong><small>B2B AI 知识库 · zh-CN</small></div><ChevronRight size={15}/></div>
      <p className="static-demo-nav-label">工作台</p>
      <nav className="static-demo-nav" aria-label="演示工作台导航">{navItems.map(({ id, label, meta, icon: Icon }) => <button key={id} className={section === id ? 'active' : ''} onClick={() => go(id)}><Icon size={16}/><span>{label}</span><em>{meta}</em></button>)}</nav>
      <div className="static-demo-sidebar-bottom"><div className="static-demo-readonly"><ShieldCheck size={15}/><span><strong>静态演示模式</strong><small>数据仅用于展示，不会写入</small></span></div><button className="static-demo-exit" onClick={onExit}>返回产品首页</button></div>
    </aside>

    <main className="static-demo-main">
      <header className="static-demo-topbar"><button className="static-demo-menu" onClick={() => setNavOpen(true)} aria-label="打开导航"><Menu size={20}/></button><div className="static-demo-breadcrumb"><span>CoreNote 示例项目</span><ChevronRight size={14}/><strong>{sectionTitle}</strong></div><div className="static-demo-top-actions"><span className="static-demo-status"><span/>演示数据已加载</span><button onClick={() => flash('在线演示不连接真实模型，也不会写入真实数据。')}><CircleAlert size={15}/>使用说明</button></div></header>
      <div className="static-demo-content">
        <div className="static-demo-banner"><div><span className="static-demo-eyebrow"><Activity size={13}/> STATIC DEMO · READ ONLY</span><h1>基于真实证据做 GEO 决策</h1><p>用一个完整的示例项目，快速了解从 Query、模型回答到竞品与内容行动的闭环。</p></div><button onClick={() => go('queries')}>查看 Query 证据 <ArrowUpRight size={16}/></button></div>
        {section === 'overview' && <Overview onNavigate={go} />}
        {section === 'queries' && <QueryView onNotice={flash} />}
        {section === 'baseline' && <BaselineView onNavigate={go} />}
        {section === 'diagnosis' && <DiagnosisView onNavigate={go} />}
        {section === 'research' && <ResearchView onNavigate={go} />}
        {section === 'content' && <ContentView onNotice={flash} />}
        {section === 'assets' && <AssetsView onNotice={flash} />}
        {section === 'reports' && <ReportsView onNotice={flash} />}
        {section === 'monitoring' && <MonitoringView onNotice={flash} />}
      </div>
      {notice && <div className="static-demo-toast"><CheckCircle2 size={17}/>{notice}</div>}
    </main>
  </div>
}

function PageHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="static-demo-page-heading"><div><span>{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><span className="static-demo-updated"><span/>最近一次更新 · 2026-09-28</span></div> }
function StatCard({ label, value, delta, tone = '' }: { label: string; value: string; delta: string; tone?: string }) { return <div className={`static-demo-stat ${tone}`}><span>{label}</span><strong>{value}</strong><small><TrendingUp size={13}/>{delta}</small></div> }
function Overview({ onNavigate }: { onNavigate: (id: DemoSection) => void }) { return <><PageHeading eyebrow="WORKSPACE OVERVIEW" title="项目状态，一眼看清" description="围绕同一批 Query，串联模型回答、引用来源、竞品位置和内容行动。"/><div className="static-demo-stat-grid"><StatCard label="品牌提及率" value="64%" delta="较上次 +12%"/><StatCard label="引用覆盖率" value="58%" delta="较上次 +8%" tone="amber"/><StatCard label="竞品平均位置" value="#2.4" delta="较上次提升 0.6 位"/><StatCard label="待处理机会" value="08" delta="3 个 P0 缺口" tone="rose"/></div><div className="static-demo-grid two"><section className="static-demo-card chart-card"><div className="static-demo-card-head"><div><span className="card-kicker">VISIBILITY TREND</span><h3>可见度趋势</h3></div><span className="pill positive">近 30 天 +18%</span></div><div className="static-demo-chart"><div className="chart-y"><span>80</span><span>60</span><span>40</span><span>20</span><span>0</span></div><svg viewBox="0 0 640 220" role="img" aria-label="品牌可见度趋势图"><path className="chart-grid" d="M0 25H640 M0 75H640 M0 125H640 M0 175H640"/><path className="chart-area" d="M0 180 C75 162 92 166 145 142 S220 142 265 118 S330 134 380 104 S450 90 500 70 S575 72 640 35 V220 H0Z"/><path className="chart-line" d="M0 180 C75 162 92 166 145 142 S220 142 265 118 S330 134 380 104 S450 90 500 70 S575 72 640 35"/><circle cx="640" cy="35" r="5"/></svg></div><div className="chart-x"><span>09/01</span><span>09/08</span><span>09/15</span><span>09/22</span><span>09/28</span></div></section><section className="static-demo-card"><div className="static-demo-card-head"><div><span className="card-kicker">NEXT ACTIONS</span><h3>下一步建议</h3></div><ArrowUpRight size={17}/></div><div className="static-demo-action-list"><button onClick={() => onNavigate('diagnosis')}><CircleAlert size={17}/><span><strong>补齐中文品类解释页</strong><small>P0 · 影响 1 个高价值 Query</small></span><ChevronRight size={16}/></button><button onClick={() => onNavigate('content')}><PenLine size={17}/><span><strong>生成 FAQ 内容简报</strong><small>P1 · 已关联 4 条证据</small></span><ChevronRight size={16}/></button><button onClick={() => onNavigate('monitoring')}><BellRing size={17}/><span><strong>设置每周复测提醒</strong><small>持续观察品牌提及变化</small></span><ChevronRight size={16}/></button></div></section></div><section className="static-demo-card"><div className="static-demo-card-head"><div><span className="card-kicker">PROJECT FLYWHEEL</span><h3>从回答证据到内容行动</h3></div><span className="static-demo-muted">只读演示</span></div><div className="static-demo-flow"><div><span>01</span><SearchCheck/><strong>定义 Query</strong><small>统一问题集</small></div><ChevronRight/><div><span>02</span><Globe2/><strong>采集回答</strong><small>保留原始证据</small></div><ChevronRight/><div><span>03</span><Radar/><strong>识别缺口</strong><small>竞品与来源对比</small></div><ChevronRight/><div><span>04</span><PenLine/><strong>形成行动</strong><small>人工发布与复测</small></div></div></section></> }
function QueryView({ onNotice }: { onNotice: (message: string) => void }) { return <><PageHeading eyebrow="01 · QUERY RESEARCH" title="Query 证据" description="同一条问题在不同模型中的回答、提及与引用，统一在这里查看。"/><div className="static-demo-toolbar"><div className="static-demo-filter"><SearchCheck size={16}/>全部 Query <ChevronRight size={14}/></div><span>3 条示例 Query · 5 个模型平台</span></div><section className="static-demo-card query-table"><div className="query-table-head"><span>问题</span><span>意图</span><span>品牌状态</span><span>提及率</span><span>来源</span></div>{queries.map((query) => <button key={query.text} className="query-row" onClick={() => onNotice('静态演示：已打开该 Query 的证据详情。')}><strong>{query.text}</strong><span>{query.intent}</span><span className={query.mention === '未提及' ? 'text-rose' : query.mention === '部分提及' ? 'text-amber' : 'text-green'}>{query.mention}</span><span>{query.rate}</span><small>{query.source}</small><ChevronRight size={15}/></button>)}</section></> }
function BaselineView({ onNavigate }: { onNavigate: (id: DemoSection) => void }) { return <><PageHeading eyebrow="02 · PLATFORM BASELINE" title="真实平台测试" description="展示不同模型对同一 Query 的回答差异，以及证据是否完整。"/><div className="static-demo-stat-grid compact"><StatCard label="已测试平台" value="5" delta="全部已连接"/><StatCard label="已完成 Query" value="12" delta="本轮完成率 100%"/><StatCard label="保留回答" value="60" delta="均可回溯"/></div><section className="static-demo-card"><div className="static-demo-card-head"><div><span className="card-kicker">MODEL COVERAGE</span><h3>平台测试状态</h3></div><span className="pill positive">本轮已完成</span></div><div className="platform-grid">{['豆包','元宝','DeepSeek','Kimi','千问'].map((name, index) => <div className="platform-item" key={name}><span className="platform-logo">{name.slice(0, 1)}</span><div><strong>{name}</strong><small>{index === 1 ? '回答已保存' : '已完成 · 2026-09-28'}</small></div><CheckCircle2 size={17}/></div>)}</div></section><div className="static-demo-callout"><ClipboardCheck size={18}/><div><strong>真实采集与静态演示的边界</strong><p>这里展示的是已脱敏的样例回答，不代表 GitHub Pages 正在连接模型。要运行真实采集，请在本地启动 API 和 Browser Agent。</p></div><button onClick={() => onNavigate('queries')}>查看证据 <ChevronRight size={15}/></button></div></> }
function DiagnosisView({ onNavigate }: { onNavigate: (id: DemoSection) => void }) { return <><PageHeading eyebrow="03 · GEO DIAGNOSIS" title="GEO 诊断与基线" description="把提及、位置、引用和竞品差距，转成可以执行的优先级。"/><div className="static-demo-diagnosis-hero"><div><span className="card-kicker">VISIBILITY SCORE</span><strong>64<span>/100</span></strong><p>当前品牌在目标 Query 集中的综合可见度</p></div><div className="score-ring"><div>64<small>VISIBILITY</small></div></div></div><div className="diagnosis-grid"><section className="static-demo-card"><div className="static-demo-card-head"><h3>高优先级缺口</h3><span className="pill danger">3 项待处理</span></div>{[['P0','中文品类解释不足','建议补充“知识图谱 + 可追溯问答” FAQ'],['P0','准确性表述存在风险','建立禁止性表述检查'],['P1','英文场景资产不足','产出面向小团队的 use case 页面']].map(([priority, title, detail]) => <div className="gap-row" key={title}><span className={`priority ${priority.toLowerCase()}`}>{priority}</span><div><strong>{title}</strong><small>{detail}</small></div><ChevronRight size={15}/></div>)}</section><section className="static-demo-card"><div className="static-demo-card-head"><h3>行动闭环</h3><span className="static-demo-muted">示例</span></div><div className="mini-funnel"><div><strong>64%</strong><span>品牌被提及</span></div><div><strong>58%</strong><span>有来源引用</span></div><div><strong>42%</strong><span>进入推荐前列</span></div></div><button className="static-demo-link-button" onClick={() => onNavigate('content')}>基于缺口生成内容策略 <ArrowUpRight size={15}/></button></section></div></> }
function ResearchView({ onNavigate }: { onNavigate: (id: DemoSection) => void }) { return <><PageHeading eyebrow="04 · COMPETITOR RESEARCH" title="行业与竞品研究" description="围绕同一 Query 分析不同链接和竞品，不再重复填写无效表单。"/><div className="static-demo-research-grid"><section className="static-demo-card"><div className="static-demo-card-head"><div><span className="card-kicker">QUERY LENS</span><h3>知识图谱 AI 知识库选型</h3></div><span className="pill positive">已分析 8 个链接</span></div><div className="competitor-bars"><div><span>CoreNote</span><b style={{width:'64%'}}/><strong>64</strong></div><div><span>Notion</span><b style={{width:'52%'}}/><strong>52</strong></div><div><span>Slab</span><b style={{width:'35%'}}/><strong>35</strong></div><div><span>语雀</span><b style={{width:'28%'}}/><strong>28</strong></div></div></section><section className="static-demo-card"><div className="static-demo-card-head"><h3>竞品结论</h3><Radar size={17}/></div><p className="static-demo-insight">竞品被引用的页面更集中在“选型标准、场景解释、对比表格”三类内容。CoreNote 的产品页具备事实，但缺少可以被模型复用的结构化解释。</p><button className="static-demo-link-button" onClick={() => onNavigate('content')}>查看内容机会 <ArrowUpRight size={15}/></button></section></div><section className="static-demo-card"><div className="static-demo-card-head"><h3>引用来源变化</h3><span className="static-demo-muted">按最近一轮基线</span></div><div className="evidence-list">{evidence.map(([title, url, kind, strength]) => <div key={url}><Link2 size={16}/><div><strong>{title}</strong><small>{url}</small></div><span>{kind}</span><em>{strength}</em></div>)}</div></section></> }
function ContentView({ onNotice }: { onNotice: (message: string) => void }) { return <><PageHeading eyebrow="05 · CONTENT STRATEGY" title="内容策略与智能写作" description="基于诊断缺口和已核验引用，形成可人工审核的内容草稿。"/><div className="static-demo-content-grid"><section className="static-demo-card"><div className="static-demo-card-head"><div><span className="card-kicker">RECOMMENDED BRIEF</span><h3>中文｜知识图谱 AI 知识库选型 FAQ</h3></div><span className="pill warning">待审核</span></div><div className="brief-meta"><span>官网知识指南</span><span>zh-CN</span><span>关联 4 条证据</span></div><ol className="brief-outline"><li><strong>先解释问题</strong><small>什么是带来源追溯的企业知识库</small></li><li><strong>给出选型标准</strong><small>知识图谱、权限、引用和协作</small></li><li><strong>补充场景对比</strong><small>与传统云盘和通用笔记的差异</small></li></ol><button className="static-demo-primary" onClick={() => onNotice('静态演示：内容编辑器不会写入真实数据。')}>打开示例草稿 <ArrowUpRight size={15}/></button></section><section className="static-demo-card markdown-preview"><div className="static-demo-card-head"><h3>Markdown 预览</h3><span>只读</span></div><div><h4>如何选择支持来源追溯的 AI 知识库？</h4><p>选择知识库时，除了回答是否准确，还应关注答案是否能回到原始资料、是否便于团队复核，以及内容是否适合持续维护。</p><hr/><h4>你可以重点比较的 4 个维度</h4><p>知识结构 · 权限边界 · 引用证据 · 团队协作</p></div></section></div></> }
const demoChannels: Array<{ name: string; detail: string; Icon: typeof Globe2 }> = [['官网 / CMS','官网内容管理后台',Globe2],['微信公众号','微信公众平台创作中心',FileText],['知乎','知乎创作中心',PenLine],['掘金','掘金创作中心',BookOpenCheck],['B 站','B 站创作中心',Activity],['自定义渠道','粘贴你的发布入口',Link2]].map(([name, detail, Icon]) => ({ name: name as string, detail: detail as string, Icon: Icon as typeof Globe2 }))
function AssetsView({ onNotice }: { onNotice: (message: string) => void }) { return <><PageHeading eyebrow="06 · PUBLISHING PREP" title="知识资产与发布准备" description="准备好内容后，由人手动打开对应创作中心完成发布。系统不代投放。"/><div className="static-demo-channel-grid">{demoChannels.map(({ name, detail, Icon }) => <button key={name} onClick={() => onNotice(`静态演示：将打开${name}的发布入口。`)}><span className="channel-icon"><Icon size={19}/></span><span><strong>{name}</strong><small>{detail}</small></span><ArrowUpRight size={16}/></button>)}</div><div className="static-demo-callout neutral"><Users size={18}/><div><strong>人工发布边界</strong><p>复制内容、打开渠道、人工登录与发布；发布后把 URL 登记回来，下一轮监控才能复测引用变化。</p></div></div></> }
function ReportsView({ onNotice }: { onNotice: (message: string) => void }) { return <><PageHeading eyebrow="07 · REPORT CENTER" title="报告中心" description="把当前项目的可见度、缺口、竞品和行动建议整理成一份可分享的结果。"/><div className="static-demo-report-grid"><div className="static-demo-report-cover"><span>GEO COMPASS</span><strong>CoreNote</strong><p>2026 Q3 · GEO 诊断报告</p><div><span>64</span><small>可见度评分</small></div></div><section className="static-demo-card"><div className="static-demo-card-head"><h3>报告内容</h3><span className="pill positive">已生成</span></div>{['执行摘要','Query 证据与模型分布','竞品与引用来源','优先级缺口','内容与发布行动'].map((item, index) => <div className="report-row" key={item}><span>0{index + 1}</span><strong>{item}</strong><CheckCircle2 size={16}/></div>)}<button className="static-demo-primary" onClick={() => onNotice('静态演示：报告导出已模拟完成，未生成真实文件。')}>查看示例报告 <ArrowUpRight size={15}/></button></section></div></> }
function MonitoringView({ onNotice }: { onNotice: (message: string) => void }) { return <><PageHeading eyebrow="OPERATIONS · MONITORING" title="持续监控" description="发布后用同一批 Query 复测，持续观察提及、引用与竞品变化。"/><div className="static-demo-stat-grid"><StatCard label="监控 Query" value="12" delta="每周一复测"/><StatCard label="本周可见度" value="64%" delta="较上周 +6%"/><StatCard label="异常提醒" value="02" delta="需要人工确认" tone="rose"/></div><div className="static-demo-grid two"><section className="static-demo-card"><div className="static-demo-card-head"><h3>异常与变化提醒</h3><span className="pill danger">2 条待处理</span></div><div className="alert-row"><CircleAlert size={17}/><div><strong>“知识库选型” Query 品牌位置下降</strong><small>DeepSeek · 从第 2 位变为第 4 位 · 2 天前</small></div></div><div className="alert-row amber"><BellRing size={17}/><div><strong>新引用来源：developer.example.com</strong><small>建议复核页面是否可长期访问</small></div></div></section><section className="static-demo-card"><div className="static-demo-card-head"><h3>模型平台分布</h3><span className="static-demo-muted">最近 30 天</span></div><div className="model-distribution">{[['豆包','28%'],['DeepSeek','24%'],['Kimi','20%'],['元宝','16%'],['千问','12%']].map(([name, value]) => <div key={name}><span>{name}</span><b><i style={{width:value}}/></b><strong>{value}</strong></div>)}</div></section></div><button className="static-demo-link-button" onClick={() => onNotice('静态演示：复测任务不会真实调度。')}>查看 Query 监控明细 <ArrowUpRight size={15}/></button></> }
